--DROP SEQUENCE USER_ID_SEQ;
CREATE SEQUENCE USER_ID_SEQ
MINVALUE 1
MAXVALUE 999999999999
START WITH 1
INCREMENT BY 1
NOCACHE;

--DROP SEQUENCE ITEM_ID_SEQ;
CREATE SEQUENCE ITEM_ID_SEQ
MINVALUE 1
MAXVALUE 999999999999
START WITH 1
INCREMENT BY 1
NOCACHE;

--DROP SEQUENCE ORDER_ID_SEQ;
CREATE SEQUENCE ORDER_ID_SEQ
MINVALUE 1
MAXVALUE 999999999999
START WITH 1
INCREMENT BY 1
NOCACHE;

DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS ORDER_DETAILS;
DROP TABLE IF EXISTS FOOD_ITEMS;
CREATE TABLE USERS(
	USER_ID INT(20) NOT NULL,
	FISRT_NAME VARCHAR(50) NOT NULL,
	MIDDLE_NAME VARCHAR(50),
	LAST_NAME VARCHAR(50) NOT NULL,
	LOGIN_NAME VARCHAR(20) NOT NULL,
	PASSWORD VARCHAR(255) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	PHONE INT(11) NOT NULL,
	STATUS VARCHAR(4),
	ADDRESS VARCHAR(255) NOT NULL,
	CREATED_ON DATE NOT NULL,
	CONSTRAINT USER_ID_PK PRIMARY KEY (USER_ID),
	CONSTRAINT LOGIN_NAME_PK UNIQUE (LOGIN_NAME)
);
CREATE TABLE FOOD_ITEMS (
	ITEM_ID INT(12) NOT NULL,
	ITEM_NAME VARCHAR(20) NOT NULL,
	TYPE VARCHAR(20) NULL,
	DESCRIPTION VARCHAR(255),
	PRICE DOUBLE(20) NOT NULL,
	STATUS VARCHAR(4),
	CREATED_ON DATE NOT NULL,	
	CONSTRAINT ITEM_ID_PK PRIMARY KEY (ITEM_ID)
);

CREATE TABLE ORDER_DETAILS(
	ORDER_ID INT(12) NOT NULL,
	USER_ID INT(20) NOT NULL,
	ITEM_ID INT(12) NOT NULL,
	QUANTITY INT(5) NOT NULL,
	STATUS VARCHAR(4),
	DESCRIPTION VARCHAR(255),
	CREATED_ON DATE NOT NULL,
	CONSTRAINT ORDER_ID_PK PRIMARY KEY (ORDER_ID)
);

